#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: data/debian/download_metadata'; exit)
. $PWD/config # import config


DIR="${DIRECTORY[data]}/debian/debtags/$(date -u +%F)"

mkdir -p "$DIR"
wget -P "$DIR" http://debtags.alioth.debian.org/tags/tags-current.gz

