#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: data/debian/download_metadata'; exit)
. $PWD/config # import config


DIR="${DIRECTORY[data]}/debian/popcon/$(date -u +%F)"

mkdir -p "$DIR"
wget -P "$DIR" http://popcon.debian.org/all-popcon-results.txt.gz

