#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: data/debian/download_metadata'; exit)
. $PWD/config # import config

HOST="ftp.br.debian.org"
DIR="${DIRECTORY[data]}/debian"

rsync -avm --include "Packages.gz" --include "Sources.gz" --include "Release" --include "*/" --exclude "*" $HOST::debian/dists $DIR
rsync -avm --include "*.list.gz" --include "*/" --exclude "*" $HOST::debian-cd $DIR
rsync -avm --include "*.packages" --include "*/" --exclude "*" $HOST::debian-cd $DIR

