#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: data/debian/download_metadata'; exit)
. $PWD/config # import config

wget -P $DEBIANDATADIR http://popcon.debian.org/all-popcon-results.txt.gz

