#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: filter/selectors_with_sf_in_homepage_body'; exit)
. $PWD/config # import config


SELECT="select distinct name from Selectors"
HAS_HOMEPAGE="(homepage is not null and homepage != '')"

sqlite3 $DB "$SELECT where $HAS_HOMEPAGE" \
| while read NAME; do
  QUERY="\W\(\($NAME.s\(f\|ourceforge\).net\)\|\(s\(f\|ourceforge\).net/projects/$NAME\)\)\W"
  FILE="${DIRECTORY[data]}/pages/ustream/$NAME.html"

  if [ -s "$FILE" ] && (cat $FILE | grep -q "$QUERY"); then
    echo "$NAME"
  fi
done



