#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: filter/selectors_with_upstream_host_in_sf_homepage_body'; exit)
. $PWD/config # import config


SELECT="select distinct name, homepage from Selectors"
HAS_HOMEPAGE="(homepage is not null and homepage != '')"

sqlite3 $DB "$SELECT where $HAS_HOMEPAGE" \
| tr "|" " " \
| while read NAME URL; do
  QUERY=$(ruby -ruri -e "puts URI.parse('$URL').host" 2> ruby.error)
  FILE="${DIRECTORY[data]}/pages/sforge/$NAME.html"

  if [ -s "$FILE" ] && (cat $FILE | grep -q "$QUERY"); then
    echo "$NAME"
  fi
done

