#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: data/download_homepages'; exit)
. $PWD/config # import config

. ${DIRECTORY[script]}/utils/progress # import progress
. ${DIRECTORY[script]}/utils/jobqueue # import jobqueue

JOBS=128

SUCCESS="${DIRECTORY[work]}/$$.success"
TMPFILES=" $SUCCESS"

function download
{
  REPOSITORY="$1"
  URL="$(echo $2 | sed 's/<\(.*\)>/\1/g' | sed 's/.*http:\/\/>//g')"
  EXTENSION="$3"
  FILE=${DIRECTORY[data]}/pages/$REPOSITORY/$ID.$EXTENSION
  [ -s "$FILE" ] && return
  [ -z "$URL"  ] && return
  trap "rm -fr $FILE.tmp" EXIT
  wget -T 30 -t 3 -qO - -B "$URL" "$URL" > $FILE.tmp
  touch $FILE
  [ $(stat -c '%s' $FILE.tmp) -gt $(stat -c '%s' $FILE) ] \
  && (mv $FILE.tmp $FILE; echo "$ID $URL $FILE" >> $SUCCESS)
  rm -fr $FILE.tmp
}

function download_all
{
  ID=$1
  SQL="select homepage from Selectors where name = '$ID'"
  URL=$(sqlite3 $DB "$SQL;")
  download 'ustream' "$URL" 'html'
  download 'debian/lenny' "packages.debian.org/lenny/$ID" 'html'
  download 'sforge' "sourceforge.net/projects/$ID" 'html'
}

FINISH="kill -TERM -$$; rm -fr $TMPFILES; echo -e '\nMay the Force be with you!'"
trap "$FINISH" EXIT

echo -n > $SUCCESS

SQL="select distinct name from Selectors join Projects using (name);"
sqlite3 $DB "$SQL" | run_queue $JOBS "download_all"

echo
echo "New pages:"
cat $SUCCESS
echo "Total found: $(cat $SUCCESS | wc -l)"

eval "$FINISH"

echo -e "\007"

