#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: report/diverge'; exit)
. $PWD/config # import config

. ${DIRECTORY[script]}/utils/progress # import progress
. ${DIRECTORY[script]}/utils/jobqueue # import jobqueue

JOBS=8
ORIGINLIST="${DIRECTORY[data]}/lists/intersection.list"
DESTLIST="${DIRECTORY[data]}/lists/diverge.list"

function check_programming_language
{
  FILE="${DIRECTORY[data]}/debian/tags-current"
  [ -s "$FILE" ] || return
  LIST0=$(
    sh ${DIRECTORY[script]}/report/fetch_debian_tag $FILE 'implemented-in' \
    | cut -d\  -f2- \
    | tr "[:upper:]" "[:lower:]" \
    | sort \
    | uniq
  )
  [ -n "$LIST0" ] || return

  FILE="${DIRECTORY[data]}/pages/sforge/$ID.html"
  [ -s "$FILE" ] || return
  LIST1=$(
    sh ${DIRECTORY[script]}/report/fetch_sforge_tag $FILE 'Programming Language' \
    | cut -d\  -f2- \
    | tr "[:upper:]" "[:lower:]" \
    | sort \
    | uniq
  )
  [ -n "$LIST1" ] || return

  RESULT=$(diff -Bw --changed-group-format='' --unchanged-group-format='%=' \
    <(echo "LIST0") <(echo "LIST1") | wc -l)
  [ "$RESULT" -eq 0 ] || return
  
  echo $ID
}

function check
{
  ID="$1"
  check_programming_language
}

FINISH="kill -TERM -$$; rm -fr $TMPFILES; echo -e '\nMay the Force be with you!'"
trap "$FINISH" EXIT

rm -fr $DESTLIST

date
cat $ORIGINLIST | run_queue $JOBS "check"
#echo 'a7xpg' | run_queue $JOBS "check"

touch $DESTLIST
echo; date; echo "sorting..."
sort $DESTLIST | uniq > $DESTLIST.sort; mv $DESTLIST.sort $DESTLIST
  
echo
echo "Total found: $(cat $DESTLIST | wc -l)"

rm -fr $TMPFILES

