#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: report/diverge'; exit)
. $PWD/config # import config

. ${DIRECTORY[script]}/utils/progress # import progress
. ${DIRECTORY[script]}/utils/jobqueue # import jobqueue

JOBS=8
ORIGINLIST="${DIRECTORY[data]}/lists/match.list"
DESTLIST="${DIRECTORY[data]}/lists/diverge.list"
FILTER="${DIRECTORY[script]}/filter/sf/details.xsl"

function check_programming_language
{
  FILE="${DIRECTORY[data]}/debian/tags-current"
  [ -s "$FILE" ] || return
  PROGRAMMING_LANGUAGE=$(
    cat $FILE \
    | grep "^$ID:" \
    | cut -d\  -f 2- \
    | sed 's/, /\n/g' \
    | grep '^implemented-in' \
    | sed 's/.*:://g' \
    | tr "[:upper:]" "[:lower:]" \
    | sed 's/todo/\n/g'
  )
  [ -n "$PROGRAMMING_LANGUAGE" ] || return
  
  FILE="${DIRECTORY[data]}/pages/sforge/$ID.html"
  [ -s "$FILE" ] || return
  LIST=$(
    xsltproc --html --stringparam 'NAME' 'Programming Language:' $FILTER $FILE \
    | tail -n +2 \
    | head -n -1 \
    | tr "[:upper:]" "[:lower:]" \
    | sort
  )
  [ -n "$LIST" ] || return
  
  RESULT=$(diff -Bw --changed-group-format='' --unchanged-group-format='%=' \
  <(echo "$PROGRAMMING_LANGUAGE") <(echo "$LIST") | wc -l)
  [ "$RESULT" -eq 0 ] || return
  
  echo $ID
}

function check
{
  ID="$1"
  check_programming_language >> $DESTLIST
}

FINISH="kill -TERM -$$; rm -fr $TMPFILES; echo -e '\nMay the Force be with you!'"
trap "$FINISH" EXIT

rm -fr $DESTLIST

date
cat $ORIGINLIST | run_queue $JOBS "check"
#echo 'gnome-rdp' | run_queue $JOBS "check"

touch $DESTLIST
echo; date; echo "sorting..."
sort $DESTLIST | uniq > $DESTLIST.sort; mv $DESTLIST.sort $DESTLIST
  
echo
echo "Total found: $(cat $DESTLIST | wc -l)"

rm -fr $TMPFILES

