#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: report/summary'; exit)
. $PWD/config # import config


declare -A SELECT=(
  [projects]="select distinct name from Projects"
  [selectors]="select distinct name from Selectors"
  [join]="select distinct name from Selectors join Projects using (name)"
  [joinhp]="select distinct name, homepage from Selectors join Projects using (name)"
)

declare -A CONDITION=(
  [has_homepage]="(homepage is not null and homepage != '')"
  [has_homepage_with_sf]="(homepage like '%sourceforge.net%' or homepage like '%sf.net%')"
  [has_description_with_sf]="(description like '%sourceforge.net/projects/'||name||'%' or description like '%'||name||'.sourceforge.net%' or description like '%'||name||'.sf.net%' or description like '%sf.net/projects/'||name||'%')"
)

SQL="${SELECT[joinhp]} where ${CONDITION[has_homepage]} and not ${CONDITION[has_homepage_with_sf]}"
sqlite3 $DB "select name from ($SQL);" | sort | \
diff --changed-group-format='%=' --unchanged-group-format='' \
- ${DIRECTORY[data]}/lists/references.list > ${DIRECTORY[data]}/lists/noreferences.list


function report
{
  FILE="${DIRECTORY[data]}/lists/$1.list"
  [ -z "$SQL" ] || sqlite3 $DB "$SQL;" > $FILE
  echo "$DESCRIPTION" $(cat $FILE | wc -l) "($1)"
}

SQL="${SELECT[projects]}"
DESCRIPTION='Projects (SourceForge):'
report 'projects'

SQL="${SELECT[selectors]}"
DESCRIPTION='Selectors (Debian 5.0.6-i386-main):'
report 'selectors'

SQL="${SELECT[projects]} union ${SELECT[selectors]} except ${SELECT[join]}"
DESCRIPTION='Identifiers (project/selector) symmetric difference:'
report 'difference'

SQL="${SELECT[join]}"
DESCRIPTION='Identifiers (project/selector) intersection:'
report 'intersection'

SQL="${SELECT[joinhp]} where not ${CONDITION[has_homepage]}"
DESCRIPTION='... seletor without homepage:'
report 'nohomepage'

SQL="${SELECT[joinhp]} where ${CONDITION[has_homepage]}"
DESCRIPTION='... seletor with homepage:'
report 'homepage'

SQL="${SELECT[joinhp]} where ${CONDITION[has_homepage_with_sf]}"
DESCRIPTION='... ... seletor URL with SF substring:'
report 'subsourceforge'

SQL="${SELECT[joinhp]} where ${CONDITION[has_homepage]} and not ${CONDITION[has_homepage_with_sf]}"
DESCRIPTION='... ... seletor URL without SF substring:'
report 'nosubsourceforge'

SQL=''
DESCRIPTION='... ... ... homepage with references to counterpart:'
report 'references'

SQL=''
DESCRIPTION='... ... ... homepage without references to counterpart:'
report 'noreferences'

SQL="${SELECT[joinhp]} where ${CONDITION[has_description_with_sf]}"
DESCRIPTION='... description with SF substring:'
report 'description_with_sf'

