#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: report/summary'; exit)
. $PWD/config # import config


function projects
{
  sqlite3 $DB "select count(distinct name) from Projects;"
}

function selectors
{
  sqlite3 $DB "select count(distinct name) from Selectors;"
}

function projects_and_selectors_with_common_names
{
  sqlite3 $DB "select count(distinct name) from Projects join Selectors using (name)"
}

function selectors_with_sf_in_homepage_url
{
  sh ${DIRECTORY[script]}/filter/selectors_with_sf_in_homepage_url | wc -l
}

function selectors_with_sf_in_homepage_body
{
  sh ${DIRECTORY[script]}/filter/selectors_with_sf_in_homepage_body | wc -l
}

function selectors_with_sf_in_description
{
  sh ${DIRECTORY[script]}/filter/selectors_with_sf_in_description | wc -l
}

function selectors_with_upstream_host_in_sf_homepage_body
{
  sh ${DIRECTORY[script]}/filter/selectors_with_upstream_host_in_sf_homepage_body | wc -l
}

echo "Projects in database: $(projects)"
echo "Selectors in database: $(selectors)"
echo "Selectors with a project with the same name in database: $(projects_and_selectors_with_common_names)"
echo "Selectors with SourceForge in homepage url: $(selectors_with_sf_in_homepage_url)"
echo "Selectors with SourceForge in homepage body: $(selectors_with_sf_in_homepage_body)"
echo "Selectors with SourceForge in description: $(selectors_with_sf_in_description)"
echo "Selectors with upstream host reference in SourceForge homepage body: $(selectors_with_upstream_host_in_sf_homepage_body)"


