#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/debian/associate_selectors'; exit)
. $PWD/config # import config


echo 'Associating selectors to projects'

SQLFILE="${DIRECTORY[work]}/associate_selectors.sql"

function sql
{
  echo "$1" >> $SQLFILE
}

function execute_sql
{
  cat $SQLFILE | sqlite3 $DB 2> $SQLFILE.error
}

function filter_selectors
{
  sh ${DIRECTORY[script]}/filter/selectors_with_sf_in_homepage_url
  sh ${DIRECTORY[script]}/filter/selectors_with_sf_in_homepage_body
  sh ${DIRECTORY[script]}/filter/selectors_with_upstream_url_in_sf_homepage_body
}

function generate_sql
{
  filter_selectors | while read NAME; do
    sql "update or ignore Selectors set project_id = (select id from Projects where name = '$NAME') where name = '$NAME';"
  done
}

echo "[$(date +%T)] Generating SQL"; generate_sql
echo "[$(date +%T)] Executing SQL"; execute_sql
echo "[$(date +%T)] Done"

