#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/debian/import_popcon'; exit)
. $PWD/config # import config


echo 'Importing Popcon data'

SQLFILE="${DIRECTORY[work]}/import_popcon.sql"

function sql
{
  echo "$1" >> $SQLFILE
}

function execute_sql
{
  cat $SQLFILE | sqlite3 $DB 2> $SQLFILE.error
}

FILE="${DIRECTORY[data]}/debian/all-popcon-results.txt.gz"
MTIME=$(echo $(date -d "$(stat -c %y $FILE)"))

function generate_sql
{
  zcat $FILE | grep '^Package' | cut -d\  -f2- | \
  while read PACKAGE INST VOTE RECENT NOFILES; do
    sql "insert into SelectorStatistics select null, id, '$MTIME', '$INST' from Selectors where name = '$PACKAGE';"
  done
}

echo "[$(date +%T)] Generating SQL"; generate_sql
echo "[$(date +%T)] Executing SQL"; execute_sql
echo "[$(date +%T)] Done"

