#!/bin/bash

PROGRESS="${DIRECTORY[work]}/$$.progress"
TMPFILES+=" $PROGRESS"

echo -n > $PROGRESS

function progress
{
  TOTAL="$1"
  LENGTH=$(echo "$TOTAL" | wc -c)
  echo >> $PROGRESS
  CURRENT="$(cat $PROGRESS | wc -l)"
  printf "\rProgress: %${LENGTH}d/$TOTAL" "$CURRENT"
}

