#!/bin/bash

PROGRESS="${DIRECTORY[work]}/$$.progress"
TMPFILES+=" $PROGRESS"

echo -n > $PROGRESS

function progress
{
  TOTAL="$1"
  PREFIX="${2:-Progress:}"
  LENGTH=$(echo "$TOTAL" | wc -c)
  echo >> $PROGRESS
  CURRENT="$(cat $PROGRESS | wc -l)"
  printf "\r$PREFIX %${LENGTH}d/$TOTAL" "$CURRENT" >&2
}

