#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/prepare'; exit)
. $PWD/config # import config

SCHEMASQL="$DBDIR/schema.sql"
VIEWSSQL="$DBDIR/views.sql"
DEBIANSQL="$WORKDIR/debian.sql"
DBOSSSQL="$WORKDIR/dboss.sql"
GITIGNORE="$WORKDIR/.gitignore"

ALLFILES=$(echo $DEBIANSQL{,.log} $DBOSSSQL{,.log} $DB $GITIGNORE)

echo 'Cleaning'
rm -f $ALLFILES

echo 'Creating .gitignore'
cat $GITIGNORE <(echo "$ALLFILES" | tr ' ' "\n") | sort | uniq > $GITIGNORE

echo 'Creating DB'
[ -s $SCHEMASQL ] || exit 1 #checks schema SQL
cat $SCHEMASQL | sqlite3 $DB #loads schema SQL
cat $VIEWSSQL | sqlite3 $DB #loads views SQL

echo; date; echo 'Importing Debian metadata'
sh $SCRIPTDIR/db/debian/import_packages | tee -a $DEBIANSQL | sqlite3 $DB 2> $DEBIANSQL.log

echo; date; echo 'Importing Popcon data'
sh $SCRIPTDIR/db/debian/import_popcon | tee -a $DEBIANSQL | sqlite3 $DB 2> $DEBIANSQL.log

echo; date; echo 'Importing Dboss categories'
sh $SCRIPTDIR/db/dboss/import_categories | tee -a $DBOSSSQL | sqlite3 $DB 2> $DBOSSSQL.log

echo; date
ls -lh $WORKDIR/

