#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/dboss/import_categories'; exit)
. $PWD/config # import config


cat ${DIRECTORY[data]}/dboss/sourceforge/proj_topics.csv | \
tr "[:upper:]" "[:lower:]" | \
sed 's/^#.*$//g' | \
sed 's/^"\|"$//g' | \
sed 's/",\|,"/ /g' | \
while read NAME CODE CATEGORY; do
  echo "insert or ignore into Categories (name) values ('$CATEGORY');"
  echo "insert or ignore into Projects_have_Categories select p.id, c.id from Projects as p, Categories as c where p.name = '$NAME' and c.name = '$CATEGORY';"
done

