#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/dboss/import_categories'; exit)
. $PWD/config # import config


echo 'Importing Dboss categories'

SQLFILE="${DIRECTORY[work]}/import_descriptions.sql"

function sql
{
  echo "$1" >> $SQLFILE
}

function execute_sql
{
  cat $SQLFILE | sqlite3 $DB 2> $SQLFILE.error
}

function generate_sql
{
  cat ${DIRECTORY[data]}/dboss/sourceforge/proj_topics.csv | \
  tr "[:upper:]" "[:lower:]" | \
  sed 's/^#.*$//g' | \
  sed 's/^"\|"$//g' | \
  sed 's/",\|,"/ /g' | \
  while read NAME CODE CATEGORY; do
    sql "insert or ignore into Categories (name) values ('$CATEGORY');"
    sql "insert or ignore into Projects (name) values ('$NAME');"
    sql "insert or ignore into Projects_have_Categories select p.id, c.id from Projects as p, Categories as c where p.name = '$NAME' and c.name = '$CATEGORY';"
  done
}

echo "[$(date %T)] Generating SQL"; generate_sql
echo "[$(date %T)] Executing SQL"; execute_sql
echo "[$(date %T)] Done"

