#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/dboss/import_projects'; exit)
. $PWD/config # import config


SQLFILE="${DIRECTORY[work]}/import_projects.sql"

function sql
{
  echo "$1" >> $SQLFILE
}

cat ${DIRECTORY[data]}/dboss/sourceforge/proj_unixname.txt | \
while read NAME; do
  sql "insert or ignore into Projects (name) values ('$NAME');"
done

cat $SQLFILE | sqlite3 $DB 2> $SQLFILE.error

