#!/bin/bash

[ -s "$PWD/config" ] || \
(echo 'From the script directory, run: db/dboss/import_projects'; exit)
. $PWD/config # import config


echo 'Importing Dboss projects list'

SQLFILE="${DIRECTORY[work]}/import_projects.sql"

function sql
{
  echo "$1" >> $SQLFILE
}

function execute_sql
{
  cat $SQLFILE | sqlite3 $DB 2> $SQLFILE.error
}

function generate_sql
{
  cat ${DIRECTORY[data]}/dboss/sourceforge/proj_unixname.txt | \
  while read NAME; do
    sql "insert or ignore into Projects (name) values ('$NAME');"
  done
}

echo "[$(date +%T)] Generating SQL"; generate_sql
echo "[$(date +%T)] Executing SQL"; execute_sql
echo "[$(date +%T)] Done"

